"""N = 50 scale check (plan sections 5.8 and 7).

The core grid is a controlled mechanism study at N = 7. Network-level pollution
claims are not credible at that scale alone, so a reduced condition set is
re-run at N = 50 with an identical logging schema, and agreement in the
*direction* of the timing and tone effects is the external-validity evidence.

OASIS is the right tool for populations of this size and is used when it is
importable. It is not a dependency of this package: the core study needs a
per-round payoff ledger with cost debiting and end-of-episode veracity
resolution, which OASIS does not provide out of the box, so the engine in
``nudgesim.env`` is authoritative for the payoff accounting in either mode. When
OASIS is absent the scale check runs the same engine on a 50-node topology, and
every record says which path produced it -- the two are not interchangeable and
are never pooled in analysis.
"""

from __future__ import annotations

from dataclasses import dataclass

from nudgesim.agents.persona import SocietySpec, scaled_society_spec
from nudgesim.data.topology import MotifLibrary


def oasis_available() -> bool:
    try:  # pragma: no cover - depends on the optional dependency being present
        import oasis  # noqa: F401
    except Exception:
        return False
    return True


def scale_check_backend_note() -> str:
    return (
        "oasis"
        if oasis_available()
        else "nudgesim-engine-at-N50 (OASIS not installed; not an OASIS result)"
    )


@dataclass(frozen=True)
class ScaleCheckSpec:
    """The reduced condition set re-run at scale (plan section 5.8).

    "Best and worst tone x both timings, one backbone, 10 seeds each" -- 4 cells,
    40 episodes. Which tone is best and which is worst is read off the N = 7
    results rather than assumed, so both tones are carried and the comparison is
    made in analysis.
    """

    n_agents: int = 50
    seeds: int = 10
    backbone: str = "surrogate-cautious"
    horizon: int = 12

    @property
    def society(self) -> SocietySpec:
        return scaled_society_spec(self.n_agents)


def build_scale_library(spec: ScaleCheckSpec, *, seed: int = 0, n_threads: int = 60) -> MotifLibrary:
    """Topologies for the scale check, generated by the same cascade process.

    Real PHEME threads rarely reach 50 nodes, so the scale-check topologies come
    from the surrogate cascade generator in both online and offline modes; this
    is stated in the results rather than glossed, because it means the scale
    check tests scale-dependence of the *mechanism*, not of PHEME-shaped
    cascades specifically.
    """
    return MotifLibrary.synthetic(
        n_threads=n_threads, motif_size=spec.n_agents, seed=seed
    ).with_min_reach(
        1,
        spec.society.all_ids,
        intervener_role=spec.society.intervener_id,
        citizen_roles=spec.society.citizen_ids,
    )
